interface ResponsiveImageProps {
  /** Path under /images without width or extension, e.g. `projects/echo`. */
  base: string
  widths: readonly number[]
  sizes: string
  width: number
  height: number
  className?: string
  /** Eager, high-priority fetch for above-the-fold imagery such as the hero. */
  priority?: boolean
}

// Decorative imagery generated by scripts/optimise-images.ts: AVIF with a WebP fallback.
export function ResponsiveImage({
  base,
  widths,
  sizes,
  width,
  height,
  className,
  priority = false,
}: ResponsiveImageProps) {
  const srcSet = (format: 'avif' | 'webp') => widths.map((w) => `/images/${base}-${w}.${format} ${w}w`).join(', ')

  return (
    <picture className={className}>
      <source type="image/avif" srcSet={srcSet('avif')} sizes={sizes} />
      <img
        src={`/images/${base}-${widths[widths.length - 1]}.webp`}
        srcSet={srcSet('webp')}
        sizes={sizes}
        width={width}
        height={height}
        alt=""
        loading={priority ? 'eager' : 'lazy'}
        fetchPriority={priority ? 'high' : 'auto'}
        decoding={priority ? 'auto' : 'async'}
      />
    </picture>
  )
}
