interface ResponsiveImageProps {
  /** Path under /images without width or extension, e.g. `projects/echo`. */
  base: string
  widths: readonly number[]
  sizes: string
  width: number
  height: number
  className?: string
  /** Eager, high-priority fetch for above-the-fold imagery such as the hero. */
  priority?: boolean
}

// Decorative imagery generated by scripts/optimise-images.ts: AVIF with a WebP fallback.
//
// Both formats are <source>s and the <img> carries no src or srcset. React sets attributes on the <img> before
// inserting it into the <picture>, and WebKit (Safari included) starts an eager load at that moment, when there are no
// <source> siblings yet: it fetched the WebP, then the AVIF once inserted, downloading the hero twice. Measured in
// Playwright's WebKit and in Safari; Chromium and Firefox wait. With no src on the detached <img> there is nothing
// to fetch until it is in place. tests/e2e/images.spec.ts guards this.
export function ResponsiveImage({
  base,
  widths,
  sizes,
  width,
  height,
  className,
  priority = false,
}: ResponsiveImageProps) {
  const srcSet = (format: 'avif' | 'webp') => widths.map((w) => `/images/${base}-${w}.${format} ${w}w`).join(', ')

  return (
    <picture className={className}>
      <source type="image/avif" srcSet={srcSet('avif')} sizes={sizes} />
      <source type="image/webp" srcSet={srcSet('webp')} sizes={sizes} />
      <img
        width={width}
        height={height}
        alt=""
        loading={priority ? 'eager' : 'lazy'}
        fetchPriority={priority ? 'high' : 'auto'}
        decoding={priority ? 'auto' : 'async'}
      />
    </picture>
  )
}
